spring:
  datasource:
    url: jdbc:mysql://114.71.137.154:52208/spring?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: project
    password: 1234
  mvc:
    converters:
      preferred-json-mapper: gson

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true              
        
        
  output:
    ansi:
      enabled: always
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

server:
  port: 8000

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
